#include "wled.h"

/*
 * CubeConnect button-flash scaffold for this WLED 17 checkout.
 * Wire a normally-open momentary button between the configured GPIO and GND.
 *
 * References: https://github.com/wled/wled-usermod-example
 * Local API examples: usermods/EXAMPLE/usermod_v2_example.cpp
 * Rendering contract: wled00/FX_fcn.cpp, WS2812FX::show(). This version blends
 * segment buffers into a separate output buffer before calling the overlay.
 * Filling that output buffer leaves effect data and frozen segments intact.
 */

// AI: below section was generated by an AI
class CubeConnectUsermod : public Usermod {
private:
  static constexpr uint32_t DEBOUNCE_MS = 35;
  static constexpr uint32_t PHASE_MS = 250;
  static constexpr uint8_t PHASE_COUNT = 6; // red, black, red, black, red, black
  // Private out-of-tree ID, unused in this checkout. Keep below 0x80 (core IDs).
  // Reserve a public ID with WLED before combining with unrelated external mods.
  static constexpr uint16_t MOD_ID = 0x7F;
  static constexpr PinOwner PIN_OWNER = static_cast<PinOwner>(MOD_ID);
  static const char NAME[];
  static const char ENABLED[];
  static const char BUTTON_PIN[];

  bool _enabled = true;
  int8_t _buttonPin = -1;
  int8_t _allocatedPin = -1;
  bool _configPending = false;
  bool _pinError = false;
  bool _updating = false;

  bool _rawPressed = false;
  bool _stablePressed = false;
  uint32_t _rawChangedAt = 0;

  bool _flashing = false;
  bool _phaseShown = false;
  uint8_t _phase = 0;
  uint32_t _phaseStartedAt = 0;

  // Request a normal composed frame; there is no preset or segment to restore.
  void stopFlash() {
    if (!_flashing) return;
    _flashing = false;
    _phaseShown = false;
    strip.trigger();
  }

  // Apply hardware changes in setup/loop, never inside a settings callback.
  void configureButton() {
    _configPending = false;
    stopFlash();
    if (_allocatedPin >= 0) {
      pinMode(_allocatedPin, INPUT);
      PinManager::deallocatePin(_allocatedPin, PIN_OWNER);
      _allocatedPin = -1;
    }

    _pinError = false;
    if (!_enabled || _buttonPin < 0) return;
    // This wiring requires an internal pull-up. Classic ESP32 GPIO34-39 are
    // input-only and have none; ESP8266 GPIO16 likewise lacks INPUT_PULLUP.
    if (!PinManager::isPinOk(_buttonPin, false) || PinManager::isReadOnlyPin(_buttonPin)
#ifdef ESP8266
        || _buttonPin == 16
#endif
        || !PinManager::allocatePin(_buttonPin, false, PIN_OWNER)) {
      _pinError = true;
      DEBUG_PRINTLN(F("CubeConnect: button GPIO unavailable or lacks pull-up"));
      return;
    }

    _allocatedPin = _buttonPin;
    pinMode(_allocatedPin, INPUT_PULLUP);
    // A button held at boot/reconfiguration must be released before triggering.
    _rawPressed = _stablePressed = digitalRead(_allocatedPin) == LOW;
    _rawChangedAt = millis();
  }

public:
  void setup() override { configureButton(); }

  // Debounce both edges without delays. Busy presses are consumed, not queued.
  void loop() override {
    if (_configPending) configureButton();
    if (!_enabled || _allocatedPin < 0) return;

    const uint32_t now = millis();
    const bool pressed = digitalRead(_allocatedPin) == LOW;
    if (pressed != _rawPressed) {
      _rawPressed = pressed;
      _rawChangedAt = now;
    }
    if (_rawPressed != _stablePressed && uint32_t(now - _rawChangedAt) >= DEBOUNCE_MS) {
      _stablePressed = _rawPressed;
      if (_stablePressed && !_flashing && !_updating && realtimeMode == REALTIME_MODE_INACTIVE) {
        _flashing = true;
        _phase = 0;
        _phaseShown = false;
      }
    }

    // Realtime streams own their buffer. Do not overwrite or interrupt them.
    if (_updating || realtimeMode != REALTIME_MODE_INACTIVE) stopFlash();
    if (_flashing && (!_phaseShown || uint32_t(now - _phaseStartedAt) >= PHASE_MS)) strip.trigger();
  }

  // Time each phase from a rendered frame, so a slow loop cannot skip flashes.
  void handleOverlayDraw() override {
    if (!_flashing) return;
    if (_updating || realtimeMode != REALTIME_MODE_INACTIVE) {
      stopFlash();
      return;
    }

    const uint32_t now = millis();
    if (_phaseShown && uint32_t(now - _phaseStartedAt) >= PHASE_MS) {
      if (++_phase >= PHASE_COUNT) {
        stopFlash();
        return; // this frame already contains the original WLED display
      }
      _phaseShown = false;
    }
    if (!_phaseShown) {
      _phaseStartedAt = now;
      _phaseShown = true;
    }

    // Cover every configured LED, including segment gaps. For the 8x8 matrix
    // WLED must be configured for 64 LEDs; row wiring does not affect a fill.
    // WLED still applies master brightness, gamma and its current limiter.
    strip.fill((_phase & 1) == 0 ? RGBW32(255, 0, 0, 0) : 0);
  }

  void onUpdateBegin(bool init) override {
    _updating = init;
    stopFlash();
  }

  // WLED persists these values and builds the Usermods settings form from them.
  void addToConfig(JsonObject& root) override {
    JsonObject top = root.createNestedObject(FPSTR(NAME));
    top[FPSTR(ENABLED)] = _enabled;
    top[FPSTR(BUTTON_PIN)] = _buttonPin;
  }

  // Validate before narrowing to int8_t; missing settings request default saving.
  bool readFromConfig(JsonObject& root) override {
    JsonObject top = root[FPSTR(NAME)];
    bool enabled = _enabled;
    int pin = _buttonPin;
    bool complete = !top.isNull();
    complete &= getJsonValue(top[FPSTR(ENABLED)], enabled);
    if (top[FPSTR(BUTTON_PIN)].is<int>()) {
      pin = top[FPSTR(BUTTON_PIN)].as<int>();
      if (pin < -1 || pin >= WLED_NUM_PINS) {
        pin = -1;
        complete = false;
      }
    } else {
      pin = -1;
      complete = false;
    }
    if (enabled != _enabled || pin != _buttonPin || _pinError) _configPending = true;
    _enabled = enabled;
    _buttonPin = static_cast<int8_t>(pin);
    return complete;
  }

  void appendConfigData() override {
    oappend(F("addInfo('CubeConnect:button-pin',1,'GPIO to GND button; -1 disables input. Use a free GPIO with an internal pull-up.');"));
    oappend(F("addInfo('CubeConnect:enabled',1,'Three red flashes, 250 ms on / 250 ms off.');"));
  }

  // WLED's Info dialog expects an array for each usermod information item.
  void addToJsonInfo(JsonObject& root) override {
    JsonObject user = root["u"];
    if (user.isNull()) user = root.createNestedObject("u");
    JsonArray status = user.createNestedArray(FPSTR(NAME));
    if (!_enabled) status.add(F("Disabled"));
    else if (_configPending) status.add(F("Applying button configuration"));
    else if (_pinError) status.add(F("GPIO unavailable or lacks internal pull-up"));
    else if (_allocatedPin < 0) status.add(F("Select button-pin in Config > Usermods"));
    else if (_updating) status.add(F("Firmware update in progress"));
    else if (realtimeMode != REALTIME_MODE_INACTIVE) status.add(F("Paused during realtime input"));
    else status.add(_flashing ? F("Flashing") : F("Ready"));
  }

  uint16_t getId() override { return MOD_ID; }
};

const char CubeConnectUsermod::NAME[] PROGMEM = "CubeConnect";
const char CubeConnectUsermod::ENABLED[] PROGMEM = "enabled";
const char CubeConnectUsermod::BUTTON_PIN[] PROGMEM = "button-pin";

static CubeConnectUsermod cubeConnectUsermod;
REGISTER_USERMOD(cubeConnectUsermod);
// AI: end
